# Site Settings
title: Yaqin Tang
email: ytangchn@gmail.com
description: Yaqin Tang is a software engineer, she graduated from WINLAB, Rutgers University.
baseurl: ""
url: "http://yaqintang.github.io"
twitter_username: yaqintang
github_username: yaqintang
logo: "/images/favicon.png"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-seo-tag