# Site Settings
# start on console with command: jekyll serve --config _config.yml, _config_dev.yml
title: Yaqin Tang
email: ytangchn@gmail.com
description: Yaqin Tang is a full-time software engineer. She graduated from winlab, Rutgers university, where she focused on mobile computing, wireless networks and visible light communication.
baseurl: ""
url: "http://localhost:4000"
twitter_username: yaqintang
github_username: yaqintang
logo: "/images/favicon.png"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-seo-tag